config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'api'

urlpatterns = [
    path('', views.companies_view, name = 'home'),
    path('addEmployee/<int:company_id>/', views.add_employee, name = 'add_employee'),
]

main/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)


class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()

    # Each employee can have only one company.
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='employees', null = True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all().order_by('first_name'), empty_label=None)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main.models import Company
from .forms import EmployeeForm

# Create your views here.


def companies_view(request):
    return render(request, 'companies.html', {"companies": Company.objects.all()})


def add_employee(request, company_id):
    company = Company.objects.get(id = company_id)

    # if request is post then get the employee and assign it to the current company
    if request.method == 'POST':
        form = EmployeeForm(request.POST)

        if form.is_valid():

            employee = form.cleaned_data['employee']
            employee.company = company
            employee.save()

            return redirect('/')
    else:
        form = EmployeeForm()

    payload = {'form': form, 'company' : company}

    return render(request, 'add_employee.html', payload)

templates/add_employee.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <title>Add Employee to {{ company.name }}</title>
</head>

<body>
    <h4>Add Employee to {{ company.name }}</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>

<script>
    $(document).ready(function () {
        $('#id_employee').select2();
    });
</script>

</html>

templates/companies.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>

<body>
    <table>
        <tr>
            <th style="width: 20%;">Company</th>
            <th>Employees</th>
        </tr>
        {% for company in companies %}
        <tr>
            <td>{{ company.name }} <a href="{% url 'api:add_employee' company.id %}">(Add Employee)</a></td>
            <td>{{ company.employees.all|join:', ' }}</td>
        </tr>
        {% endfor %}
    </table>
</body>

</html>